let inputWidth = prompt("Enter the width");;
let inputHeight = prompt("Enter the height");
let width = parseInt(inputWidth);
let height = parseInt(inputHeight);
let area = width * height;
document.write("Enter width: " + width);
document.write("<br>");
document.write("Enter height: " + height);
document.write("<br>");
document.write("This area is: " + area);